"""initial_schema

Revision ID: 29ab4e8079f1
Revises: 
Create Date: 2026-04-21 17:07:49.608516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29ab4e8079f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('key_prefix', sa.Text(), nullable=False),
    sa.Column('owner_email', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('cards',
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('era', sa.Text(), nullable=False),
    sa.Column('local_id', sa.Text(), nullable=False),
    sa.Column('total', sa.Text(), nullable=True),
    sa.Column('name_ja', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('rarity', sa.Text(), nullable=True),
    sa.Column('set_name_ja', sa.Text(), nullable=True),
    sa.Column('set_name_en', sa.Text(), nullable=True),
    sa.Column('set_release_date', sa.Date(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('tier', sa.Text(), server_default='mid', nullable=False),
    sa.Column('is_tracked', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index('idx_cards_era', 'cards', ['era'], unique=False)
    op.create_index('idx_cards_tier_tracked', 'cards', ['tier', 'is_tracked'], unique=False, postgresql_where=sa.text('is_tracked = true'))
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('cards_attempted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cards_succeeded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scrape_runs_source_started', 'scrape_runs', ['source', sa.literal_column('started_at DESC')], unique=False)
    op.create_table('card_scrape_state',
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.PrimaryKeyConstraint('card_id', 'source')
    )
    op.create_table('price_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('cardrush', 'snkrdunk', name='source_enum', create_constraint=True), nullable=False),
    sa.Column('source_type', sa.Enum('listing', 'sold', name='source_type_enum', create_constraint=True), nullable=False),
    sa.Column('condition', sa.Enum('RAW_A', 'RAW_A_MINUS', 'RAW_B', 'RAW_C', name='condition_enum', create_constraint=True), nullable=False),
    sa.Column('price_jpy', sa.Integer(), nullable=False),
    sa.Column('stock_qty', sa.Integer(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('scrape_run_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_points_card_cond_time', 'price_points', ['card_id', 'condition', sa.literal_column('observed_at DESC')], unique=False)
    op.create_index('uq_price_points_idem', 'price_points', ['card_id', 'source', 'source_type', 'condition', 'price_jpy', 'observed_at', sa.literal_column("coalesce(external_url, '')")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_price_points_idem', table_name='price_points')
    op.drop_index('idx_price_points_card_cond_time', table_name='price_points')
    op.drop_table('price_points')
    op.drop_table('card_scrape_state')
    op.drop_index('idx_scrape_runs_source_started', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('idx_cards_tier_tracked', table_name='cards', postgresql_where=sa.text('is_tracked = true'))
    op.drop_index('idx_cards_era', table_name='cards')
    op.drop_table('cards')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
