"""Round-trip-stable YAML writer for the ``data/cards`` tree.

Rules:

- Uses ``ruamel.yaml`` for output to preserve key order and produce a stable
  diff-friendly layout.
- Preserves any existing file that starts with ``# manual: true`` — those are
  human-curated overrides and should never be overwritten by bootstrap.
- Leaves existing files that *don't* carry the manual flag alone only when
  their content would not change (byte-equal after re-render).
"""

from __future__ import annotations

import io
import logging
import pathlib
from dataclasses import dataclass
from typing import Any

from ruamel.yaml import YAML

from watari_catalog.paths import card_yaml_path, cards_set_dir

logger = logging.getLogger(__name__)


MANUAL_MARKER = "# manual: true"


def _yaml_writer() -> YAML:
    y = YAML()
    y.default_flow_style = False
    y.allow_unicode = True
    y.width = 1000
    y.indent(mapping=2, sequence=4, offset=2)
    return y


@dataclass
class CardYamlPayload:
    """Structured shape written to each ``data/cards/{SET}/{local_id}.yml`` file."""

    set_code: str
    local_id: str                 # zero-padded (e.g. "089")
    name_ja: str | None
    name_en: str | None
    rarity_code: str | None
    category: str                 # 'card' | 'trainer' | 'energy'
    image: str | None
    illustrator: str | None
    prints: list[str]             # variant slugs including 'normal'
    sources: dict[str, Any]


@dataclass
class EmitResult:
    written: int = 0
    skipped_manual: int = 0
    unchanged: int = 0

    def record(self, *, written: bool, manual: bool, unchanged: bool) -> None:
        if manual:
            self.skipped_manual += 1
        elif unchanged:
            self.unchanged += 1
        elif written:
            self.written += 1


def _is_manual(path: pathlib.Path) -> bool:
    if not path.exists():
        return False
    head = path.read_text(encoding="utf-8").splitlines()[:3]
    return any(line.strip().lower().startswith("# manual: true") for line in head)


def _serialize(payload: CardYamlPayload) -> str:
    """Produce the YAML body for a card file (without header banner)."""
    display_set_code = payload.set_code.lower()
    doc: dict[str, Any] = {
        "set_code": display_set_code,
        "local_id": payload.local_id,
        "name_ja": payload.name_ja,
        "name_en": payload.name_en,
        "rarity_code": payload.rarity_code,
        "category": payload.category,
        "image": payload.image,
        "illustrator": payload.illustrator,
        "prints": list(payload.prints),
        "sources": payload.sources,
    }
    # Drop keys that would render as 'null' *only* when they're optional nested
    # dicts with no content — everything else keeps an explicit ``null`` so
    # reviewers see which fields weren't filled.
    if not doc["sources"]:
        doc["sources"] = {}
    if not doc["prints"]:
        doc["prints"] = ["normal"]

    buf = io.StringIO()
    _yaml_writer().dump(doc, buf)
    return buf.getvalue()


def _banner(set_code: str, local_id: str) -> str:
    display_set_code = set_code.lower()
    return (
        f"# {display_set_code} #{local_id}. Generated by "
        f"`python -m watari_catalog bootstrap-set`.\n"
        f"# To freeze a manually-edited value, add `# manual: true` on line 1.\n"
    )


def write_card_yaml(payload: CardYamlPayload, result: EmitResult) -> pathlib.Path:
    """Emit a single card YML file. Honors the ``# manual: true`` opt-out."""
    cards_set_dir(payload.set_code).mkdir(parents=True, exist_ok=True)
    path = card_yaml_path(payload.set_code, payload.local_id)

    body = _serialize(payload)
    new_text = _banner(payload.set_code, payload.local_id) + body

    if _is_manual(path):
        logger.debug("skip manual: %s", path)
        result.record(written=False, manual=True, unchanged=False)
        return path

    if path.exists() and path.read_text(encoding="utf-8") == new_text:
        result.record(written=False, manual=False, unchanged=True)
        return path

    path.write_text(new_text, encoding="utf-8")
    result.record(written=True, manual=False, unchanged=False)
    return path


def load_card_yaml(path: pathlib.Path) -> dict[str, Any] | None:
    """Load a YML file as a plain dict (for seed-cards)."""
    if not path.exists():
        return None
    import yaml as pyyaml  # pyyaml is fine for reading
    return pyyaml.safe_load(path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]


__all__ = [
    "CardYamlPayload",
    "EmitResult",
    "MANUAL_MARKER",
    "load_card_yaml",
    "write_card_yaml",
]
