const PK = "https://den-media.pokellector.com/logos";

// JP release order — lower number = newer. Sets without an entry sort last.
export const SET_RELEASE_ORDER: Record<string, number> = {
  // SV era (newest → oldest)
  SV11W: 0, SV11B: 1,
  SV10: 2,
  SV9A: 3, SV9: 4,
  SV8A: 5, SV8: 6,
  SV7A: 7, SV7: 8,
  SV6A: 9, SV6: 10,
  SV5A: 11, SV5M: 12, SV5K: 13,
  SV4A: 14, SV4M: 15, SV4K: 16,
  SV3A: 17, SV3: 18,
  SV2A: 19, SV2D: 20, SV2P: 21,
  SV1A: 22, SV1V: 23, SV1S: 24,
  // ME era (newest → oldest)
  M4: 0, M3: 1,
  M2A: 2, M2: 3,
  M1S: 4, M1L: 5,
  // SM era (newest → oldest)
  SM12A: 100,
  SM12: 101,
  SM11B: 102,
  SM11A: 103,
  SM11: 104,
  SM10B: 105,
  SM10A: 106,
  SMP2: 107,
  SM10: 108,
  SM9B: 109,
  SM9A: 110,
  SM9: 111,
  SM8B: 112,
  SM8A: 113,
  SM8: 114,
  SM7B: 115,
  SM7A: 116,
  SM7: 117,
  SM6B: 118,
  SM6A: 119,
  SM6: 120,
  SM5P: 121,
  SM5M: 122,
  SM5S: 123,
  SM4P: 124,
  SM4A: 125,
  SM4S: 126,
  SM3P: 127,
  SM3N: 128,
  SM3H: 129,
  SM2L: 130,
  SM2K: 131,
  SM2P: 132,
  SM1P: 133,
  SM1M: 134,
  SM1S: 135,
  SM0: 136,
  // SwSH era (newest → oldest, approximate for tie-break)
  S12A: 200,
  S12: 201,
  S11A: 202,
  S10B: 203,
  S10A: 204,
  S9A: 205,
  S9: 206,
  S8B: 207,
  S8A: 208,
  S8: 209,
  S7R: 210,
  S7D: 211,
  S6A: 212,
  S6K: 213,
  S6H: 214,
  S5A: 215,
  S5R: 216,
  S5I: 217,
  S4A: 218,
  S4: 219,
  S3A: 220,
  S3: 221,
  S2A: 222,
  S2: 223,
  S1A: 224,
  S1H: 225,
  S1W: 226,
  S11: 227,
};

export const SET_LOGO_URLS: Record<string, string> = {
  SV1A:  `${PK}/Triple-Beat.logo.366.png`,
  SV1S:  `${PK}/Scarlet-ex.logo.361.png`,
  SV1V:  `${PK}/Violet-ex.logo.362.png`,
  SV2P:  `${PK}/Snow-Hazard.logo.369.png`,
  SV2D:  `${PK}/Clay-Burst.logo.370.png`,
  SV2A:  `${PK}/Pokemon-151.logo.371.png`,
  SV3:   `${PK}/Ruler-of-the-Black-Flame.logo.368.png`,
  SV3A:  `${PK}/Raging-Surf.logo.376.png`,
  SV4A:  `${PK}/Shiny-Treasure-ex.logo.375.png`,
  SV4K:  `${PK}/Ancient-Roar.logo.381.png`,
  SV4M:  `${PK}/Future-Flash.logo.382.png`,
  SV5K:  `${PK}/Wild-Force.logo.386.png`,
  SV5M:  `${PK}/Cyber-Judge.logo.387.png`,
  SV5A:  `${PK}/Crimson-Haze.logo.391.png`,
  SV6:   `${PK}/Mask-of-Change.logo.393.png`,
  SV6A:  `${PK}/Night-Wanderer.logo.398.png`,
  SV7:   `${PK}/Stella-Miracle.logo.401.png`,
  SV7A:  `${PK}/Paradise-Dragona.logo.403.png`,
  SV8:   `${PK}/Super-Electric-Breaker.logo.405.png`,
  SV8A:  `${PK}/Terastal-Festival-ex.logo.406.png`,
  SV9:   `${PK}/Battle-Partners.logo.408.png`,
  SV9A:  `${PK}/Hot-Air-Arena.logo.411.png`,
  SV10:  `${PK}/Glory-of-Team-Rocket.logo.413.png`,
  SV11B: `${PK}/Black-Bolt.logo.414.png`,
  SV11W: `${PK}/White-Flare.logo.415.png`,
  M1L:   `${PK}/Mega-Brave.logo.416.png`,
  M1S:   `${PK}/Mega-Symphonia.logo.417.png`,
  M2:    `${PK}/Inferno-X.logo.425.png`,
  M2A:   `${PK}/MEGA-Dream-ex.logo.427.png`,
  M3:    `${PK}/Munikis-Zero.logo.428.png`,
  M4:    `${PK}/Ninja-Spinner.logo.430.png`,
  // Sword & Shield era (jp.pokellector.com)
  S1W:   `${PK}/Sword.logo.283.png`,
  S1H:   `${PK}/Shield.logo.284.png`,
  S2:    `${PK}/Rebellion-Crash.logo.291.png`,
  S3:    `${PK}/Infinity-Zone.logo.293.png`,
  S4:    `${PK}/Electrifying-Tackle.logo.297.png`,
  S5I:   `${PK}/Single-Strike-Master.logo.306.png`,
  S5R:   `${PK}/Rapid-Strike-Master.logo.307.png`,
  S6H:   `${PK}/Silver-Lance.logo.309.png`,
  S6K:   `${PK}/Jet-Black-Poltergeist.logo.310.png`,
  S7D:   `${PK}/Perfect-Skyscraper.logo.318.png`,
  S7R:   `${PK}/Blue-Sky-Stream.logo.319.png`,
  S8:    `${PK}/Fusion-ARTS.logo.326.png`,
  S9:    `${PK}/Star-Birth.logo.336.png`,
  S10D:  `${PK}/Time-Gazer.logo.341.png`,
  S10P:  `${PK}/Space-Juggler.logo.342.png`,
  S11:   `${PK}/Lost-Abyss.logo.344.png`,
  S12:   `${PK}/Paradigm-Trigger.logo.351.png`,
  S1A:   `${PK}/VMAX-Rising.logo.285.png`,
  S2A:   `${PK}/Explosive-Flame-Walker.logo.295.png`,
  S3A:   `${PK}/Legendary-Pulse.logo.294.png`,
  S4A:   `${PK}/Shiny-Star-V.logo.301.png`,
  S5A:   `${PK}/Matchless-Fighter.logo.308.png`,
  S6A:   `${PK}/Eevee-Heroes.logo.322.png`,
  S8A:   `${PK}/25th-Anniversary-Collection.logo.327.png`,
  S8B:   `${PK}/VMAX-Climax.logo.338.png`,
  S9A:   `${PK}/Battle-Region.logo.339.png`,
  S10A:  `${PK}/Dark-Phantasma.logo.343.png`,
  S10B:  `${PK}/Pokmon-GO.logo.347.png`,
  S11A:  `${PK}/Incandescent-Arcana.logo.352.png`,
  S12A:  `${PK}/VSTAR-Universe.logo.357.png`,
  // SM era (jp.pokellector.com logo assets)
  SM0:    `${PK}/Pikachu-New-Friends.logo.204.png`,
  SM1S:   `${PK}/Collection-Sun.logo.201.png`,
  SM1M:   `${PK}/Collection-Moon.logo.202.png`,
  SM1P:   `${PK}/Sun-Moon-Strengthening-Expansion.logo.200.png`,
  SM2P:   `${PK}/Strengthening-Expansion-Pack-Beyond-A-New-Challenge.logo.212.png`,
  SM2K:   `${PK}/Islands-Awaiting-You.logo.211.png`,
  SM2L:   `${PK}/Alola-Moonlight.logo.210.png`,
  SM3H:   `${PK}/Seen-the-Rainbow-Battle.logo.219.png`,
  SM3N:   `${PK}/Light-Consuming-Darkness.logo.218.png`,
  SM3P:   `${PK}/Strengthening-Expansion-Pack-Shining-Legends.logo.224.png`,
  SM4S:   `${PK}/The-Awoken-Hero.logo.226.png`,
  SM4A:   `${PK}/The-Transdimensional-Beast.logo.227.png`,
  SM4P:   `${PK}/GX-Battle-Boost.logo.228.png`,
  SM5S:   `${PK}/Ultra-Sun.logo.232.png`,
  SM5M:   `${PK}/Ultra-Moon.logo.233.png`,
  SM5P:   `${PK}/Ultra-Force.logo.238.png`,
  SM6:    `${PK}/Forbidden-Light.logo.235.png`,
  SM6A:   `${PK}/Dragon-Storm.logo.236.png`,
  SM6B:   `${PK}/Champion-Road.logo.237.png`,
  SM7:    `${PK}/Charisma-of-the-Cracked-Sky.logo.242.png`,
  SM7A:   `${PK}/Thunderclap-Spark.logo.243.png`,
  SM7B:   `${PK}/Fairy-Rise.logo.240.png`,
  SM8:    `${PK}/Explosive-Impact.logo.258.png`,
  SM8A:   `${PK}/Dark-Order.logo.245.png`,
  SM8B:   `${PK}/Ultra-Shiny-GX.logo.241.png`,
  SM9:    `${PK}/Tag-Bolt.logo.260.png`,
  SM9A:   `${PK}/Night-Unison.logo.262.png`,
  SM9B:   `${PK}/Full-Metal-Wall.logo.263.png`,
  SM10:   `${PK}/Double-Blaze.logo.266.png`,
  SM10A:  `${PK}/GG-End.logo.267.png`,
  SM10B:  `${PK}/Sky-Legends.logo.268.png`,
  SM11:   `${PK}/Miracle-Twins.logo.277.png`,
  SM11A:  `${PK}/Remix-Bout.logo.272.png`,
  SM11B:  `${PK}/Dream-League.logo.278.png`,
  SM12:   `${PK}/Alter-Genesis.logo.281.png`,
  SM12A:  `${PK}/Tag-Team-GX-All-Stars.logo.288.png`,
  SMP2:   `${PK}/Detective-Pikachu.logo.271.png`,
};

/** Set-symbol PNG URLs (Bulbagarden Archives). See e.g. [Alter Genesis symbol](https://bulbapedia.bulbagarden.net/wiki/File:SetSymbolAlter_Genesis.png). */
export const SET_SYMBOL_URLS: Record<string, string> = {
  M1L: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolMega_Brave.png",
  M1S: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolMega_Symphonia.png",
  M2: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolInferno_X.png",
  M2A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolMEGA_Dream_ex.png",
  M3: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolNihil_Zero.png",
  M4: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolNinja_Spinner.png",
  S10A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDark_Phantasma.png",
  S10B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolS10b.png",
  S10D: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTime_Gazer.png",
  S10P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSpace_Juggler.png",
  S11: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolLost_Abyss.png",
  S11A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolIncandescent_Arcana.png",
  S12: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolParadigm_Trigger.png",
  S12A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolVSTAR_Universe.png",
  S1A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolVMAX_Rising.png",
  S1H: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolShield.png",
  S1W: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSword.png",
  S2: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolRebellion_Crash.png",
  S2A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolExplosive_Walker.png",
  S3: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolInfinity_Zone.png",
  S3A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolLegendary_Heartbeat.png",
  S4: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolAmazing_Volt_Tackle.png",
  S4A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolShiny_Star_V.png",
  S5A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolPeerless_Fighters.png",
  S5I: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSingle_Strike_Master.png",
  S5R: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolRapid_Strike_Master.png",
  S6A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolEevee_Heroes.png",
  S6H: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSilver_Lance.png",
  S6K: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolJet-Black_Spirit.png",
  S7D: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSkyscraping_Perfection.png",
  S7R: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolBlue_Sky_Stream.png",
  S8: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolFusion_Arts.png",
  S8A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbol25th_Anniversary_Collection.png",
  S8B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolVMAX_Climax.png",
  S9: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolStar_Birth.png",
  S9A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolBattle_Region.png",
  SM0: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolPikachu_New_Friends.png",
  SM10: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDouble_Blaze.png",
  SM10A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolGG_End.png",
  SM10B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSky_Legend.png",
  SM11: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolMiracle_Twin.png",
  SM11A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolRemix_Bout.png",
  SM11B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDream_League.png",
  SM12: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolAlter_Genesis.png",
  SM12A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTag_All_Stars.png",
  SM1M: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolCollection_Moon.png",
  SM1P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSM1Plus.png",
  SM1S: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolCollection_Sun.png",
  SM2K: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolIslands_Await_You.png",
  SM2L: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolAlolan_Moonlight.png",
  SM2P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolFacing_a_New_Trial.png",
  SM3H: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTo_Have_Seen_the_Battle_Rainbow.png",
  SM3N: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDarkness_that_Consumes_Light.png",
  SM3P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolShiningLegends.png",
  SM4A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolUltradimensional_Beasts.png",
  SM4P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolGX_Battle_Boost.png",
  SM4S: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolAwakened_Heroes.png",
  SM5M: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolUltra_Moon.png",
  SM5P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolUltra_Force.png",
  SM5S: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolUltra_Sun.png",
  SM6: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolForbiddenLight.png",
  SM6A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDragon_Storm.png",
  SM6B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolChampion_Road.png",
  SM7: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSky-Splitting_Charisma.png",
  SM7A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolThunderclap_Spark.png",
  SM7B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolFairy_Rise.png",
  SM8: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSuper-Burst_Impact.png",
  SM8A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolDark_Order.png",
  SM8B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolGX_Ultra_Shiny.png",
  SM9: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTag_Bolt.png",
  SM9A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolNight_Unison.png",
  SM9B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolFull_Metal_Wall.png",
  SMP2: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolGreat_Detective_Pikachu.png",
  SV10: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolGlory_of_the_Rocket_Gang.png",
  SV11B: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolBlackBolt.png",
  SV11W: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolWhiteFlare.png",
  SV1A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTriplet_Beat.png",
  SV1S: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolScarlet_ex.png",
  SV1V: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolViolet_ex.png",
  SV2A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolPok%C3%A9mon_Card_151.png",
  SV2D: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolClay_Burst.png",
  SV2P: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSnow_Hazard.png",
  SV3: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolRuler_of_the_Black_Flame.png",
  SV3A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolRaging_Surf.png",
  SV4A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolShiny_Treasure_ex.png",
  SV4K: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolAncient_Roar.png",
  SV4M: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolFuture_Flash.png",
  SV5A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolCrimson_Haze.png",
  SV5K: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolWild_Force.png",
  SV5M: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolCyber_Judge.png",
  SV6: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTransformation_Mask.png",
  SV6A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolNight_Wanderer.png",
  SV7: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolStellar_Miracle.png",
  SV7A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolParadise_Dragona.png",
  SV8: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolSuper_Electric_Breaker.png",
  SV8A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolTerastal_Fest_ex.png",
  SV9: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolBattle_Partners.png",
  SV9A: "https://archives.bulbagarden.net/wiki/Special:FilePath/SetSymbolHot_Wind_Arena.png",
};
export const ERA_LABELS: Record<string, string> = {
  sv: "Scarlet & Violet",
  me: "Mega Evolution",
  sm: "Sun & Moon",
  sw: "Sword & Shield",
};

export const CONDITION_LABELS: Record<string, string> = {
  S: "S",
  A: "A",
  B: "B",
  D: "D",
  new: "New",
  used: "Used",
};

// Rarity sort order — higher = rarer. Unknown rarities default to 99 in the
// sort helper so they always sort to the top when sorting rarest-first.
// MA is the ME-era equivalent of SAR/UR; MUR sits above UR in the newest sets.
export const RARITY_SORT_ORDER: Record<string, number> = {
  C: 0,
  U: 1,
  R: 2,
  RR: 3,
  TR: 3,   // Trainer Gallery Rare Holo (SWSH era)
  PR: 4,   // promo — at least as rare as RR in practice
  K: 4,    // Radiant Rare (SWSH era)
  RRR: 5,
  CHR: 5,  // Character Rare (SWSH era)
  SR: 6,
  CSR: 6,  // Character Super Rare (SWSH era)
  AR: 7,
  SSR: 7,  // Shiny Double Rare (SWSH Shiny Star V / VMAX Climax)
  HR: 7,   // Hyper Rare (SM era gold full-art)
  SAR: 8,
  MA: 8,   // ME-era top-tier art rare (equivalent to SAR)
  BWR: 8,  // SV11B/W Black & White Rare (equivalent tier to SAR/MA)
  UR: 9,
  MUR: 10,
};
